import Navbar from '@components/molecules/Navbar';
import PromotedFreeGames from '@components/organisms/PromotedFreeGames';
import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={'container'}>
        <PromotedFreeGames />
        {/* <RecentFreeGames/> */}
        {/* <AllFreGames/> */}
      </main>

      <footer className="">Freezone&trade;</footer>
    </div>
  );
};

export default Home;
