import Footer from '@components/organisms/Footer';
import Navbar from '@components/organisms/Navbar';
import Head from 'next/head';
import React from 'react';

type PropTypes = {
  children: React.ReactNode;
};

export default function Layout({ children }: PropTypes) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="container mx-auto">{children}</main>
      <Footer />
    </>
  );
}
