import Footer from '@components/molecules/Footer';
import Navbar from '@components/molecules/Navbar';
import Head from 'next/head';
import React from 'react';

type PropsTypes = {
  children: React.ReactNode;
};

export default function Layout({ children }: PropsTypes) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="container mx-auto px-8">{children}</main>
      <Footer />
    </>
  );
}
